# 17 · Vectorized Miller Plane and Direction Workflows

**Where this sits in PyTex.** Planes $(hkl)$ and directions $[uvw]$ are the vocabulary
of crystallography. PyTex represents them as **batch semantic objects** — `MillerPlaneSet`
and `MillerDirectionSet` — that stay attached to a phase (so they know their metric and
symmetry) while remaining NumPy-vectorized for large-scale computation. This notebook is
the practical guide to that surface: conversions, spacings, angles, and symmetry families,
done on whole arrays at once.

## Learning goals

1. build `MillerPlaneSet`/`MillerDirectionSet` from index arrays attached to a phase;
2. convert between 3-index Miller and 4-index **Miller–Bravais** for hexagonal crystals;
3. compute **d-spacings** and **interplanar/interdirection angles**, checked against analytic values;
4. expand **symmetry families** and **project directions onto planes** — all vectorized.

## Theory

A plane's spacing and the angle between planes both come from the (reciprocal) metric
tensor (Notebook 04), so these objects must carry the phase. For **hexagonal** crystals
the 3-index Miller notation hides the three-fold symmetry of the basal plane; the
**Miller–Bravais** 4-index form $(hkil)$ with the redundant $i=-(h+k)$ restores it, so
that permuting $h,k,i$ generates the symmetry-equivalent planes. PyTex offers both and
converts losslessly. Cubic angles have clean closed forms — $\angle([100],[110])=45^\circ$,
$\angle([100],[111])=\arccos(1/\sqrt3)=54.7356^\circ$ — which we use as ground truth.
(De Graef & McHenry 2012; Hammond 2015.)

In [1]:
from __future__ import annotations

import warnings

import numpy as np

warnings.filterwarnings("ignore", message="Issues encountered while parsing CIF")
warnings.filterwarnings("ignore", message="No _symmetry_equiv_pos_as_xyz")

from pytex import (
    FrameDomain,
    Lattice,
    MillerDirectionSet,
    MillerPlaneSet,
    Phase,
    ReferenceFrame,
    SymmetrySpec,
    get_phase_fixture,
    project_directions_onto_planes,
)

np.set_printoptions(precision=4, suppress=True)

crystal = ReferenceFrame("crystal", FrameDomain.CRYSTAL, ("a", "b", "c"))
fcc = Phase(
    "fcc_demo",
    lattice=Lattice(3.6, 3.6, 3.6, 90, 90, 90, crystal_frame=crystal),
    symmetry=SymmetrySpec.from_point_group("m-3m", reference_frame=crystal),
    crystal_frame=crystal,
)

## 1 · Batch construction and d-spacings

`MillerPlaneSet.from_hkl` takes an $(n,3)$ integer array and a phase. Every operation is
then vectorized over the batch. For cubic $a=3.6$ Å the spacings must equal
$a/\sqrt{h^2+k^2+l^2}$, which we assert.

In [2]:
planes = MillerPlaneSet.from_hkl(np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]]), phase=fcc)
directions = MillerDirectionSet.from_uvw(np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]]), phase=fcc)

d = planes.d_spacings_angstrom()
analytic = np.array([3.6 / np.sqrt(n) for n in (1, 2, 3)])
print("plane indices:\n", planes.indices)
print("d-spacings (A):", np.round(d, 4))
print("a / sqrt(N)   :", np.round(analytic, 4))
assert np.allclose(d, analytic, atol=1e-9)

plane indices:
 [[1 0 0]
 [1 1 0]
 [1 1 1]]
d-spacings (A): [3.6    2.5456 2.0785]
a / sqrt(N)   : [3.6    2.5456 2.0785]


## 2 · Angles, vectorized

`angle_matrix_rad` returns the full pairwise angle matrix for a batch. Reading off the
$[100]$ row recovers the textbook cubic angles to $[110]$ ($45^\circ$) and $[111]$
($54.7356^\circ$).

In [3]:
angles = np.rad2deg(directions.angle_matrix_rad(antipodal=True))
print("direction angle matrix (deg):\n", np.round(angles, 4))
assert abs(angles[0, 1] - 45.0) < 1e-6
assert abs(angles[0, 2] - 54.7356) < 1e-3

direction angle matrix (deg):
 [[ 0.     45.     54.7356]
 [45.      0.     35.2644]
 [54.7356 35.2644  0.    ]]


## 3 · Symmetry families

`symmetry_equivalent_indices` expands each index to its full crystallographic family
under the phase symmetry, returning a padded array plus a validity mask. Under cubic
$m\bar3m$ the $\{100\}$ family has 3 distinct plane poles (antipodal pairs identified),
$\{110\}$ has 6, and $\{111\}$ has 4.

In [4]:
family_indices, mask = planes.symmetry_equivalent_indices()
sizes = mask.sum(axis=1)
print("family sizes for {100}, {110}, {111}:", sizes.tolist())
print("\n{100} family members:\n", family_indices[0, mask[0]])
assert sizes.tolist() == [3, 6, 4]

family sizes for {100}, {110}, {111}: [3, 6, 4]

{100} family members:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


## 4 · Miller–Bravais for hexagonal crystals

Now the case that really needs four indices. For HCP zirconium the basal plane is
$(0001)$ and the prism planes are $\{10\bar10\}$; the 4-index form makes their symmetry
explicit. The 3→4 conversion inserts $i=-(h+k)$; the basal spacing equals $c$ and the
prism spacing equals $\tfrac{\sqrt3}{2}a$.

In [5]:
zr = get_phase_fixture("zr_hcp").load_phase(crystal_frame=crystal)
hex_planes = MillerPlaneSet.from_hkl(np.array([[0, 0, 1], [1, 0, 0], [1, 1, 0]]), phase=zr)
print("HKL -> HKIL:\n", hex_planes.to_hkil())
print("d-spacings (A):", np.round(hex_planes.d_spacings_angstrom(), 4))
print(f"c = {zr.lattice.c:.4f},  (sqrt3/2) a = {np.sqrt(3) / 2 * zr.lattice.a:.4f}")
assert abs(hex_planes.d_spacings_angstrom()[0] - zr.lattice.c) < 1e-6

HKL -> HKIL:
 [[ 0  0  0  1]
 [ 1  0 -1  0]
 [ 1  1 -2  0]]
d-spacings (A): [5.147 2.799 1.616]
c = 5.1470,  (sqrt3/2) a = 2.7990


## 5 · Projecting directions onto planes

`project_directions_onto_planes` removes each direction's plane-normal component,
leaving its in-plane projection — the operation behind trace analysis and slip-direction
resolution. It also flags degenerate cases (a direction parallel to the normal projects
to zero). We project the cubic directions onto $\{001\}$, $\{111\}$, $\{010\}$.

In [6]:
target_planes = MillerPlaneSet.from_hkl([[0, 0, 1], [1, 1, 1], [0, 1, 0]], phase=fcc)
projected, degenerate = project_directions_onto_planes(directions, target_planes)
print("projected in-plane vectors:\n", np.round(projected, 4))
print("degenerate (dir ∥ normal) mask:\n", degenerate)

projected in-plane vectors:
 [[ 1.      0.      0.    ]
 [ 0.2357  0.2357 -0.4714]
 [ 0.5774  0.      0.5774]]
degenerate (dir ∥ normal) mask:
 [False False False]


## Summary and where to go next

- `MillerPlaneSet`/`MillerDirectionSet` are **phase-attached, vectorized** batches: they
  know their metric and symmetry while staying NumPy-fast.
- **d-spacings** and **angles** match analytic values; **Miller–Bravais** conversion makes
  hexagonal symmetry explicit; **symmetry families** and **plane projection** run on whole
  batches.
- For interactive single objects use `CrystalPlane`/`CrystalDirection`; for large-scale
  or benchmark work use these set types.

**Next:** [Notebook 04](04_phases_lattices_space_groups_and_cif.ipynb) for the metric
tensor behind spacings and angles; [Notebook 10](10_plotting_semantic_primitives.ipynb)
to plot these planes and directions stereographically.