# Vectorized Miller Plane And Direction Workflows

This tutorial shows the intended PyTex workflow for first-class Miller plane and direction objects attached to a phase.

It covers:

- vectorized creation from arrays
- hexagonal index conversion
- cartesian vectors, normals, and d-spacings
- angle matrices
- symmetry-family expansion
- projecting directions onto planes


In [1]:
from __future__ import annotations

import numpy as np

from pytex import (
    FrameDomain,
    Handedness,
    Lattice,
    MillerDirectionSet,
    MillerPlaneSet,
    Phase,
    ReferenceFrame,
    SymmetrySpec,
    angle_dir_dir_rad,
    project_directions_onto_planes,
)


In [2]:
crystal = ReferenceFrame(
    name="crystal",
    domain=FrameDomain.CRYSTAL,
    axes=("a", "b", "c"),
    handedness=Handedness.RIGHT,
)
lattice = Lattice(3.6, 3.6, 3.6, 90.0, 90.0, 90.0, crystal_frame=crystal)
symmetry = SymmetrySpec.from_point_group("m-3m", reference_frame=crystal)
phase = Phase("fcc_demo", lattice=lattice, symmetry=symmetry, crystal_frame=crystal)
phase


Phase(name='fcc_demo', lattice=Lattice(a=3.6, b=3.6, c=3.6, alpha_deg=90.0, beta_deg=90.0, gamma_deg=90.0, crystal_frame=ReferenceFrame(name='crystal', domain=<FrameDomain.CRYSTAL: 'crystal'>, axes=('a', 'b', 'c'), handedness=<Handedness.RIGHT: 'right'>, convention=ConventionSet(name='pytex_canonical', angle_convention=<AngleConvention.BUNGE_ZXZ: 'bunge_zxz'>, quaternion_order=('w', 'x', 'y', 'z'), reciprocal_convention=<ReciprocalConvention.KRONECKER_DELTA: 'kronecker_delta'>, notes=('Right-handed Cartesian frames.', 'Bunge phi1, Phi, phi2 labeling.', 'Unit quaternions stored in w, x, y, z order.', 'Reciprocal basis normalized such that a*_i dot a_j = delta_ij.')), description='', provenance=None, metadata=mappingproxy({})), provenance=None), symmetry=SymmetrySpec(name='432', point_group='m-3m', operators=array([[[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]

In [3]:
planes = MillerPlaneSet.from_hkl(
    np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]], dtype=np.int64),
    phase=phase,
)
directions = MillerDirectionSet.from_uvw(
    np.array([[1, 0, 0], [1, 1, 0], [1, 1, 1]], dtype=np.int64),
    phase=phase,
)

print("HKL -> HKIL:\n", planes.to_hkil())
print("UVW -> UVTW:\n", directions.to_UVTW())


HKL -> HKIL:
 [[ 1  0 -1  0]
 [ 1  1 -2  0]
 [ 1  1 -2  1]]
UVW -> UVTW:
 [[ 2 -1 -1  0]
 [ 1  1 -2  0]
 [ 1  1 -2  3]]


In [4]:
table = np.column_stack(
    [
        planes.indices,
        np.round(planes.normals_cartesian(), 6),
        np.round(planes.d_spacings_angstrom(), 6)[:, None],
    ]
)
print("Columns: h k l | nx ny nz | d(angstrom)")
print(table)


Columns: h k l | nx ny nz | d(angstrom)
[[ 1.        0.        0.        1.       -0.       -0.        3.6     ]
 [ 1.        1.        0.        0.707107  0.707107 -0.        2.545584]
 [ 1.        1.        1.        0.57735   0.57735   0.57735   2.078461]]


In [5]:
angle_matrix = directions.angle_matrix_rad(antipodal=True)
reference = MillerDirectionSet.from_uvw([[1, 0, 0]], phase=phase)
pairwise = angle_dir_dir_rad(directions, reference, antipodal=True)
print("Direction angle matrix (rad):\n", np.round(angle_matrix, 6))
print("Angles to <100> (rad):\n", np.round(pairwise, 6))


Direction angle matrix (rad):
 [[0.       0.785398 0.955317]
 [0.785398 0.       0.61548 ]
 [0.955317 0.61548  0.      ]]
Angles to <100> (rad):
 [0.       0.785398 0.955317]


In [6]:
equivalent_indices, mask = planes.symmetry_equivalent_indices()
first_family = equivalent_indices[0, mask[0]]
print("First plane family under cubic symmetry:\n", first_family)


First plane family under cubic symmetry:
 [[0 0 1]
 [0 1 0]
 [1 0 0]]


In [7]:
projection_planes = MillerPlaneSet.from_hkl([[0, 0, 1], [1, 1, 1], [0, 1, 0]], phase=phase)
projected, degenerate = project_directions_onto_planes(directions, projection_planes)
print("Projected direction vectors:\n", np.round(projected, 6))
print("Degenerate mask:\n", degenerate)


Projected direction vectors:
 [[ 1.        0.        0.      ]
 [ 0.235702  0.235702 -0.471405]
 [ 0.57735   0.        0.57735 ]]
Degenerate mask:
 [False False False]


The vectorized `symmetry_equivalent_indices()` surface is designed for large batches and benchmarking.
Use `symmetry_equivalents()` when you want a tuple of semantic sets for interactive work.
